// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDitzAAYusXodGYzHfNoh4WX5atjWm2Lc0',
    appId: '1:749366765101:web:71387c6d8bed3f0af07aa4',
    messagingSenderId: '749366765101',
    projectId: 'ipssi-flutter-69ca6',
    authDomain: 'ipssi-flutter-69ca6.firebaseapp.com',
    storageBucket: 'ipssi-flutter-69ca6.appspot.com',
    measurementId: 'G-SL9VJ5T7EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZo8PaGcpFC2j_DPN7Ce1zSjluTZfAHX4',
    appId: '1:749366765101:android:5ef9dc7bb6376851f07aa4',
    messagingSenderId: '749366765101',
    projectId: 'ipssi-flutter-69ca6',
    storageBucket: 'ipssi-flutter-69ca6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJPiDpSI9gsE_xvN1vZKv4dAm15SNTPZA',
    appId: '1:749366765101:ios:4d1dcce7078a582cf07aa4',
    messagingSenderId: '749366765101',
    projectId: 'ipssi-flutter-69ca6',
    storageBucket: 'ipssi-flutter-69ca6.appspot.com',
    iosClientId: '749366765101-ut7h9cn7uqil0rtqcgr4ukgvfm5k0cn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstbd233',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJPiDpSI9gsE_xvN1vZKv4dAm15SNTPZA',
    appId: '1:749366765101:ios:74f68b63d419c455f07aa4',
    messagingSenderId: '749366765101',
    projectId: 'ipssi-flutter-69ca6',
    storageBucket: 'ipssi-flutter-69ca6.appspot.com',
    iosClientId: '749366765101-tcanhbao3dt3vhpf8tph6vvcfbjrujrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstbd233.RunnerTests',
  );
}
